args <- commandArgs(trailingOnly = TRUE)
project_dir <- normalizePath(Sys.getenv("HOLTEMME_PROJECT_DIR", unset = getwd()), winslash = "/", mustWork = TRUE)
failures <- character()
pass <- function(label, detail) cat("PASS", label, "-", detail, "\n")
fail <- function(label, detail) { failures <<- c(failures, paste(label, detail, sep = " - ")); cat("FAIL", label, "-", detail, "\n") }
read_tsv <- function(path) utils::read.delim(path, stringsAsFactors = FALSE, check.names = FALSE, quote = "", comment.char = "")
registry_path <- file.path(project_dir, "config", "publication_artifact_registry.tsv")
plot_path <- file.path(project_dir, "config", "plot_registry.tsv")
data_path <- file.path(project_dir, "config", "data_manifest.tsv")
zenodo_path <- file.path(project_dir, "config", "zenodo_deposit_manifest.tsv")
if (!file.exists(registry_path)) stop("Missing publication_artifact_registry.tsv")
registry <- read_tsv(registry_path)
plots <- read_tsv(plot_path)
data <- read_tsv(data_path)
zenodo <- read_tsv(zenodo_path)
expected_labels <- c(paste("Figure", 1:5), paste0("Figure S", 1:5), paste0("Table S", 1:7))
expected_types <- c(main_figure = 5L, supplementary_figure = 5L, supplementary_table = 7L)
if (nrow(registry) == 17L) pass("artifact_count", "17 publication artifacts") else fail("artifact_count", paste("expected 17, found", nrow(registry)))
counts <- table(registry$artifact_type)
if (all(counts[names(expected_types)] == expected_types)) pass("artifact_types", "5 main figures, 5 supplementary figures, 7 supplementary tables") else fail("artifact_types", paste(capture.output(print(counts)), collapse = " "))
if (length(unique(registry$manuscript_or_si_label)) == nrow(registry) && setequal(registry$manuscript_or_si_label, expected_labels)) pass("unique_labels", "labels are explicit and unique") else fail("unique_labels", "labels are not the exact 17-item publication set")
if (all(grepl("^DP0[1-7]$", registry$data_package))) pass("single_dp", "every artifact has exactly one DP01-DP07 assignment") else fail("single_dp", "one or more rows have missing, compound, or invalid DP assignment")
figure_rows <- registry$artifact_type %in% c("main_figure", "supplementary_figure")
figure_rmd_ok <- figure_rows & nzchar(registry$analysis_step) & nzchar(registry$authoritative_rmd) & file.exists(file.path(project_dir, registry$authoritative_rmd))
if (all(figure_rmd_ok[figure_rows])) pass("figure_authority", "every figure has an analysis step and existing authoritative Rmd") else fail("figure_authority", paste(registry$artifact_id[figure_rows][!figure_rmd_ok[figure_rows]], collapse = ", "))
if (nrow(plots) == 10L && setequal(plots$artifact_id, registry$artifact_id[figure_rows])) pass("plot_registry", "all 10 paper/SI figures are registered") else fail("plot_registry", "plot registry is not exactly the 10-figure set")
if (length(grep("Supplementary_Data", paste(capture.output(utils::write.table(registry, row.names = FALSE, sep = "\t")), collapse = "\n"))) == 0L && length(grep("Supplementary_Data", paste(capture.output(utils::write.table(zenodo, row.names = FALSE, sep = "\t")), collapse = "\n"))) == 0L) pass("no_obsolete_workbooks", "no Supplementary_Data workbook is required by publication registries") else fail("no_obsolete_workbooks", "obsolete workbook reference detected")
direct_dp <- table(factor(registry$data_package, levels = paste0("DP0", 1:7)))
if (direct_dp[["DP02"]] == 0L && direct_dp[["DP06"]] == 0L) pass("intentional_empty_dps", "DP02 and DP06 have zero direct paper-facing artifacts") else fail("intentional_empty_dps", "DP02 or DP06 was assigned a direct artifact")
required_ids <- c("10.5281/zenodo.22143080", "SRP571512", "https://github.com/miloes114/EchoGo")
if (all(required_ids %in% data$external_resource_id)) pass("external_ids", "DOI, SRA accession, and EchoGO URL are represented") else fail("external_ids", "one or more required external identifiers are absent")
if (any(grepl("dcf41371b20cccb2914852dc2c0436ecba62c559", data$notes)) && !any(grepl("10\\.5281/zenodo\\.000000|SRP000000|TODO_IDENTIFIER", data$external_resource_id))) pass("external_versions", "EchoGO commit is pinned and unavailable identifiers are not invented") else fail("external_versions", "dependency pin or placeholder check failed")
if (!any(grepl("Supplementary_Data", list.files(project_dir, recursive = TRUE, full.names = FALSE)))) pass("repository_workbook_policy", "no obsolete Supplementary_Data workbook is present") else fail("repository_workbook_policy", "obsolete Supplementary_Data workbook found")
if (!any(grepl("absent|blocking", readLines(file.path(project_dir, "docs", "publication_artifact_reconciliation.md"), warn = FALSE, encoding = "UTF-8"), ignore.case = TRUE))) fail("si_correction_note", "P0 SI correction note is missing") else pass("si_correction_note", "P0 stale chemistry-caption correction is documented")
if (length(failures)) quit(status = 1L, save = "no")



